import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf('    function favoriteStorageKey()'),html.indexOf('    function getCurrentFolderWords()'));
function harness({local={기본:[]},deferPost=false}={}){
 const store=new Map([['favoriteFolders:synthetic-A',JSON.stringify(local)]]),posts=[],gets=[];
 const ctx={currentUser:{id:'synthetic-A',token:'fixture-A'},studentSessionEpoch:1,favoriteEditSerial:0,DEFAULT_FOLDER_NAME:'기본',favoriteFolders:{기본:[]},currentFavoriteFolder:'기본',console:{warn(){}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},apiGet:p=>new Promise((resolve,reject)=>gets.push({p,resolve,reject})),apiPost:p=>{const post={user:ctx.currentUser.id,state:JSON.parse(p.foldersJson)};posts.push(post);return deferPost?new Promise(resolve=>post.resolve=resolve):Promise.resolve({success:true});}};
 vm.createContext(ctx);vm.runInContext(source,ctx);
 const reset=()=>{ctx.studentSessionEpoch++;ctx.favoriteEditSerial++;ctx.currentUser={id:'synthetic-B',token:'fixture-B'};ctx.favoriteFolders={기본:['B-only']};ctx.currentFavoriteFolder='기본';};
 return{ctx,store,posts,gets,reset};
}
test('late old-account response cannot modify new state or save with new identity',async()=>{const h=harness(),pending=h.ctx.loadFavoriteFolders();h.reset();h.gets[0].resolve({success:true,folders:{기본:['A-only']}});assert.equal(await pending,false);assert.equal(h.posts.length,0);assert.deepEqual(h.ctx.favoriteFolders,{기본:['B-only']});assert.equal(h.store.has('favoriteFolders:synthetic-B'),false);});
test('late old-account read error cannot write new local storage',async()=>{const h=harness(),pending=h.ctx.loadFavoriteFolders();h.reset();h.gets[0].reject(Error('old'));assert.equal(await pending,false);assert.equal(h.posts.length,0);assert.equal(h.store.has('favoriteFolders:synthetic-B'),false);});
test('same content in different order does not create an automatic POST',async()=>{const h=harness({local:{extra:['y'],기본:['b','a']}}),pending=h.ctx.loadFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:['a','b'],extra:['y']}});assert.equal(await pending,true);assert.equal(h.posts.length,0);assert.equal(h.ctx.favoriteEditSerial,0);});
test('local-only data still merges and saves once with its original account',async()=>{const h=harness({local:{기본:['false','0'],local:['word']}}),pending=h.ctx.loadFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:['server']}});assert.equal(await pending,true);assert.equal(h.posts.length,1);assert.equal(h.posts[0].user,'synthetic-A');assert.deepEqual(h.posts[0].state,{기본:['server','false','0'],local:['word']});assert.equal(h.ctx.favoriteEditSerial,0);});
test('manual edit during read is not overwritten or resurrected',async()=>{const h=harness(),pending=h.ctx.loadFavoriteFolders();h.ctx.favoriteFolders={기본:['new-manual']};await h.ctx.saveFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:['deleted-old']}});assert.equal(await pending,false);assert.deepEqual(h.ctx.favoriteFolders,{기본:['new-manual']});assert.equal(h.posts.length,1);assert.deepEqual(h.posts[0].state,{기본:['new-manual']});});
test('a stale explicit save stops before storage and POST',async()=>{const h=harness();h.reset();assert.equal(await h.ctx.saveFavoriteFolders(1),false);assert.equal(h.posts.length,0);assert.equal(h.store.has('favoriteFolders:synthetic-B'),false);});
test('switch while original-account automatic save is pending cannot finalize new state',async()=>{const h=harness({local:{기본:['local']},deferPost:true}),pending=h.ctx.loadFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:['server']}});await new Promise(resolve=>setImmediate(resolve));assert.equal(h.posts.length,1);assert.equal(h.posts[0].user,'synthetic-A');h.reset();h.posts[0].resolve({success:true});assert.equal(await pending,false);assert.deepEqual(h.ctx.favoriteFolders,{기본:['B-only']});assert.equal(h.store.has('favoriteFolders:synthetic-B'),false);});
test('malformed remote folder state cannot trigger an automatic save',async()=>{const h=harness({local:{기본:['local']}}),pending=h.ctx.loadFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:'invalid'}});await pending;assert.equal(h.posts.length,0);assert.equal(h.ctx.favoriteFolders.기본[0],'local');});
test('guest path stays local and has no server request',async()=>{const h=harness();h.ctx.currentUser=null;assert.equal(await h.ctx.loadFavoriteFolders(),true);assert.equal(h.gets.length,0);assert.equal(h.posts.length,0);assert.equal(h.store.has('favoriteFolders:guest'),true);});
test('folder names including inherited object keys preserve own data safely',async()=>{const local=JSON.parse('{"기본":[],"toString":["local"],"__proto__":["word"]}'),h=harness({local}),pending=h.ctx.loadFavoriteFolders();h.gets[0].resolve({success:true,folders:{기본:[]}});assert.equal(await pending,true);assert.equal(h.posts.length,1);assert.deepEqual(h.posts[0].state.toString,['local']);assert.deepEqual(h.posts[0].state.__proto__,['word']);});
