import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {test}from 'node:test';
const source=fs.readFileSync(new URL('../recording/app.js',import.meta.url),'utf8');
function line(name){const found=source.split(/\r?\n/).find(l=>l.startsWith('async function '+name+'('));assert.ok(found);return found;}
function harness(response,{saving=false,loading=false}={}){const calls=[],old={targetDate:'2026-10-06',classes:[]},APP={targetDate:old.targetDate,data:old,loading,saving:new Set(saving?['C|S']:[])};
 const c={APP,Date,performance,$:()=>({textContent:''}),renderReadTiming:()=>{},ensureConnected:()=>true,setSync:()=>{},api:async(action,payload)=>{calls.push({action,payload});if(response instanceof Error)throw response;return response;},render:()=>{},toast:()=>{},renderError:()=>{},updateNetwork:()=>{}};vm.createContext(c);vm.runInContext(line('loadData')+'\n'+line('selectDate'),c);return {c,APP,calls,old};}
test('failed date read must retain displayed and save-target date identity',async()=>{const h=harness(new Error('Synthetic network failure'));await h.c.selectDate('2026-10-07');assert.equal(h.APP.data,h.old);assert.equal(h.APP.targetDate,h.APP.data.targetDate);assert.equal(h.calls[0].action,'opsDashboard');assert.equal(h.calls[0].payload.targetDate,'2026-10-07');});
test('successful date read commits date and data together',async()=>{const data={targetDate:'2026-10-07',classes:[]},h=harness(data);await h.c.selectDate(data.targetDate);assert.equal(h.APP.targetDate,data.targetDate);assert.equal(h.APP.data,data);assert.equal(h.calls.length,1);});
test('mismatched response date must not replace the displayed date or data',async()=>{const h=harness({targetDate:'2026-10-08',classes:[]});await h.c.selectDate('2026-10-07');assert.equal(h.APP.targetDate,h.old.targetDate);assert.equal(h.APP.data,h.old);});
test('initial blank date accepts the server selected date',async()=>{const data={targetDate:'2026-10-06',classes:[]},h=harness(data);h.APP.targetDate='';await h.c.loadData(false);assert.equal(h.APP.data,data);assert.equal(h.APP.targetDate,data.targetDate);});
test('date cannot switch while a student save is pending',async()=>{const h=harness({targetDate:'2026-10-07',classes:[]},{saving:true});await h.c.selectDate('2026-10-07');assert.equal(h.APP.targetDate,h.old.targetDate);assert.equal(h.calls.length,0);});
test('loading and same-date selections do not issue another request',async()=>{for(const loading of [false,true]){const h=harness({}, {loading});await h.c.selectDate(loading?'2026-10-07':'2026-10-06');assert.equal(h.calls.length,0);}});
test('successful load returns data without depending on removed diagnostics',async()=>{const data={targetDate:'2026-10-07',classes:[],requestTiming:{scope:'CURRENT_REQUEST_BEFORE_JSON',parseMs:1}},h=harness(data);assert.equal(await h.c.loadData(false,data.targetDate),data);assert.equal(h.APP.loading,false);});
