import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {test} from 'node:test';
const source=fs.readFileSync(new URL('../recording/app.js',import.meta.url),'utf8');
const fn=source.split(/\r?\n/).find(line=>line.startsWith('function renderCurrentRequestTiming('));
function render(data){const node={textContent:'기존 서버 구간'};const ctx={$:()=>node};vm.createContext(ctx);vm.runInContext(fn,ctx);ctx.renderCurrentRequestTiming(data);return node.textContent;}
test('only four numeric current request fields are added',()=>{const text=render({token:'SECRET',requestTiming:{scope:'CURRENT_REQUEST_BEFORE_JSON',parseMs:1,sessionVerificationMs:2,dispatchMs:3,preJsonTotalMs:6,studentName:'PRIVATE'}});assert.match(text,/세션 검증: 2 ms/);assert.match(text,/JSON 변환 전 합계: 6 ms/);assert.match(text,/JSON 변환·응답 전송·화면 처리 제외/);assert.doesNotMatch(text,/SECRET|PRIVATE/);});
test('old server and unknown scope preserve existing diagnostic unchanged',()=>{assert.equal(render({}),'기존 서버 구간');assert.equal(render({requestTiming:{scope:'UNKNOWN',parseMs:1}}),'기존 서버 구간');});
test('invalid values are not echoed as trusted timing',()=>{const text=render({requestTiming:{scope:'CURRENT_REQUEST_BEFORE_JSON',parseMs:'SECRET',sessionVerificationMs:-1,dispatchMs:Infinity,preJsonTotalMs:NaN}});assert.doesNotMatch(text,/SECRET|-1|Infinity|NaN/);assert.match(text,/미제공/);});
test('diagnostic issues no requests and preserves data',()=>{const data={requestTiming:{scope:'CURRENT_REQUEST_BEFORE_JSON',parseMs:1}},before=JSON.stringify(data);render(data);assert.equal(JSON.stringify(data),before);assert.doesNotMatch(fn,/fetch\(|api\(|localStorage|innerHTML/);});
test('successful validated load renders new diagnostics, failure replaces old timings',()=>{const load=source.split(/\r?\n/).find(line=>line.startsWith('async function loadData('));assert.match(load,/renderReadTiming\(data,[^;]+;renderCurrentRequestTiming\(data\)/);assert.match(load,/catch\(error\)\{renderReadTiming\(null,[^;]+,true\)/);assert.equal((load.match(/renderCurrentRequestTiming\(/g)||[]).length,1);});
