import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8').replace(/\r\n?/g,'\n');
const marker='<script>\n// Selected-body loader',offset=html.lastIndexOf(marker);assert.ok(offset>0);
const script=html.slice(offset+'<script>\n'.length,html.indexOf('\n</script>',offset));
function setup({failBody=false}={}){
 const elements=Object.fromEntries(['vocab-view','vocab-book-select','vocab-day-select','vocab-progress','vocab-search-result','favorites-view'].map(id=>[id,{value:'',innerHTML:''}]));const calls=[],renders=[];
 const row=['Book',1,'false','0',1,'b','["true"]'];
 const c={structuredClone,currentUser:{role:'student'},studentSessionEpoch:1,vocabData:[],document:{getElementById:id=>elements[id]},escapeHtml:x=>String(x),currentFavoriteFolder:'folder',favoriteFolders:{folder:['key']},sortWordsByOrder:x=>x,makeWordKey:()=> 'key',showVocabList:()=>renders.push('selected'),loadVocabBooks(){renders.push('staff-legacy-load');},loadVocabDays(){renders.push('staff-legacy-days');},searchVocab:()=>renders.push('search:'+c.vocabData.length),showFavorites:()=>renders.push('favorites:'+c.getFavoriteRows().length),getFavoriteRows(){},startFavoriteTest:()=>renders.push('test:'+c.getFavoriteRows().length),startFavoriteMeaningCheck:()=>renders.push('meaning:'+c.getFavoriteRows().length),apiGet:async p=>{calls.push(p.action);if(p.action==='getVocabBrowseCatalog')return {success:true,schema:'STUDENT_VOCAB_BROWSE_V1',books:[{bookId:'b',revisionId:'r',name:'Book',sections:[{sectionId:'s',day:'1',wordCount:1}]}]};if(p.action==='getVocabBrowseSection'){if(failBody)throw Error('BODY_INTEGRITY');return {success:true,schema:'STUDENT_VOCAB_BROWSE_V1',bookId:'b',revisionId:'r',sectionId:'s',rows:[row]};}if(p.action==='getVocabData')return {success:true,values:[['header'],row]};throw Error('UNEXPECTED_API');}};
 vm.createContext(c);vm.runInContext(script,c);return {c,elements,calls,renders,row};
}
test('real UI integration initializes metadata only and selects body without whole-table fetch',async()=>{const {c,elements,calls,renders,row}=setup();assert.equal(await c.loadVocabBooks(),true);assert.deepEqual(calls,['getVocabBrowseCatalog']);elements['vocab-book-select'].value='Book';await c.loadVocabDays();elements['vocab-day-select'].value='1';await c.showVocabList();assert.deepEqual(JSON.parse(JSON.stringify(c.vocabData[1])),row);assert.deepEqual(calls,['getVocabBrowseCatalog','getVocabBrowseSection']);assert.deepEqual(renders,['selected']);});
test('selected integrity error never silently invokes legacy full download',async()=>{const {c,elements,calls}=setup({failBody:true});await c.loadVocabBooks();elements['vocab-book-select'].value='Book';await c.loadVocabDays();elements['vocab-day-select'].value='1';await c.showVocabList();assert.equal(calls.includes('getVocabData'),false);assert.match(elements['vocab-view'].innerHTML,/BODY_INTEGRITY/);});
test('full search and all favorite actions retain explicit legacy hydration and selected data',async()=>{const {c,elements,calls,renders}=setup();await c.loadVocabBooks();elements['vocab-book-select'].value='Book';await c.loadVocabDays();elements['vocab-day-select'].value='1';await c.showVocabList();const before=JSON.stringify(c.vocabData);await c.searchVocab();await c.showFavorites();await c.startFavoriteTest();await c.startFavoriteMeaningCheck();assert.equal(JSON.stringify(c.vocabData),before);assert.equal(calls.filter(x=>x==='getVocabData').length,1);assert.deepEqual(renders.slice(1),['search:2','favorites:1','test:1','meaning:1']);});
test('old session cannot hydrate a current favorite action',async()=>{const {c,elements,calls}=setup();await c.loadVocabBooks();c.studentSessionEpoch=2;await c.showFavorites();assert.equal(calls.includes('getVocabData'),false);assert.match(elements['favorites-view'].innerHTML,/다시/);});
test('administrator and teacher preserve explicit original browse and favorite rights without student impersonation',async()=>{for(const role of ['admin','teacher']){const {c,calls,renders,row}=setup();c.currentUser={role};c.vocabData=[['header'],row];await c.loadVocabBooks();await c.loadVocabDays();await c.showFavorites();assert.deepEqual(calls,[]);assert.deepEqual(renders,['staff-legacy-load','selected','staff-legacy-days','favorites:1']);}});
test('old catalog hydration cannot populate favorites after metadata reload in the same login',async()=>{const {c,renders}=setup();await c.loadVocabBooks();const original=c.apiGet;let resolve;let bulk=0;c.apiGet=p=>p.action==='getVocabData'?(++bulk===1?new Promise(yes=>{resolve=yes;}):original(p)):original(p);const pending=c.showFavorites();await c.loadVocabBooks();resolve({success:true,values:[['old header'],['OLD']]});await pending;assert.equal(renders.length,0);await c.showFavorites();assert.equal(bulk,2);assert.deepEqual(renders,['favorites:1']);});
test('failed old book request cannot replace a newly selected book at the same Day',async()=>{const {c,elements}=setup();await c.loadVocabBooks();elements['vocab-book-select'].value='Book';await c.loadVocabDays();elements['vocab-day-select'].value='1';let reject;c.apiGet=()=>new Promise((resolve,no)=>{reject=no;});const pending=c.showVocabList();await Promise.resolve();elements['vocab-book-select'].value='Other';elements['vocab-view'].innerHTML='NEW_BOOK_SCREEN';reject(Error('OLD_BOOK_FAILURE'));await pending;assert.equal(elements['vocab-view'].innerHTML,'NEW_BOOK_SCREEN');});

