const APP={version:'7.3.0',apiKey:'allbarun.rec.apiUrl',tokenKey:'allbarun.rec.token',queueKey:'allbarun.quick.queue',cachePrefix:'allbarun.quick.cache.',recentKey:'allbarun.quick.recentStudents',examModeKey:'allbarun.quick.examMode',tab:'home',loaded:{},data:{},lastLog:null,undoTimer:null,installPrompt:null};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const val=id=>($(id)||{}).value||'';
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function syncState(text,kind=''){const e=$('sync-state');e.textContent=text;e.className='pill '+kind}
function apiUrl(){return localStorage.getItem(APP.apiKey)||''}function token(){return localStorage.getItem(APP.tokenKey)||''}
async function api(action,payload={},override={}){const url=override.url||apiUrl();if(!url)throw new Error('서버 주소가 설정되지 않았습니다.');const body={action,payload,token:override.token===undefined?token():override.token,pin:override.pin||''};const res=await fetch(url,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const text=await res.text();let json;try{json=JSON.parse(text)}catch(e){throw new Error('서버 응답을 읽지 못했습니다. 배포 주소와 권한을 확인하세요.')}if(!json.success)throw new Error(json.error&&json.error.message||'요청 실패');return json.data}
function readCache(key,maxAge=86400000){try{const x=JSON.parse(localStorage.getItem(APP.cachePrefix+key)||'null');return x&&Date.now()-x.time<maxAge?x.data:null}catch(e){return null}}
function writeCache(key,data){try{localStorage.setItem(APP.cachePrefix+key,JSON.stringify({time:Date.now(),data}))}catch(e){}}
function readQueue(){try{return JSON.parse(localStorage.getItem(APP.queueKey)||'[]')}catch(e){return[]}}function writeQueue(q){localStorage.setItem(APP.queueKey,JSON.stringify(q))}
function updateNetwork(){const online=navigator.onLine,e=$('network-state');e.textContent=online?'온라인':'오프라인';e.className='pill '+(online?'':'offline')}
async function connectServer(){const url=val('api-url').trim(),pin=val('admin-pin').trim();if(!url||!pin)return toast('주소와 PIN을 입력하세요.');syncState('연결 중','saving');try{const login=await api('login',{}, {url,pin,token:''});localStorage.setItem(APP.apiKey,url);localStorage.setItem(APP.tokenKey,login.token);$('setup-modal').classList.remove('show');toast('연결했습니다.');await loadHome(true)}catch(e){syncState('연결 오류','error');toast(e.message)}}
function ensureConnected(){if(!apiUrl()||!token()){$('api-url').value=apiUrl();$('setup-modal').classList.add('show');return false}$('setup-modal').classList.remove('show');return true}
function closeSetupIfConnected(){if(apiUrl()&&token())$('setup-modal').classList.remove('show')}
function openConnectionSettings(){closeSettings();$('api-url').value=apiUrl();$('admin-pin').value='';$('setup-modal').classList.add('show')}
function openSettings(){const mode=localStorage.getItem(APP.examModeKey)||'AUTO';if($('exam-mode-setting'))$('exam-mode-setting').value=mode;$('settings-modal').classList.add('show')}function closeSettings(){$('settings-modal').classList.remove('show')}function saveExamMode(mode){localStorage.setItem(APP.examModeKey,mode);APP.loaded.home=false;loadHome(true)}
function openModal(title,eyebrow,html){$('modal-title').textContent=title;$('modal-eyebrow').textContent=eyebrow||'';$('modal-body').innerHTML=html;$('form-modal').classList.add('show');setTimeout(bindDateRanges,0)}function closeModal(){$('form-modal').classList.remove('show')}
function currentDate(){return new Date().toISOString().slice(0,10)}function addDays(date,n){const d=new Date((date||currentDate())+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function showUndo(message,logId){APP.lastLog=logId;$('undo-text').textContent=message;$('undo-bar').classList.add('show');clearTimeout(APP.undoTimer);APP.undoTimer=setTimeout(()=>$('undo-bar').classList.remove('show'),12000)}
async function undoLastAction(){if(!APP.lastLog)return;syncState('되돌리는 중','saving');try{await api('quickUndo',{logId:APP.lastLog});$('undo-bar').classList.remove('show');APP.lastLog=null;toast('이전 상태로 복원했습니다.');await refreshCurrent(true);await loadHome(true)}catch(e){toast(e.message)}finally{syncState('최신','')}}
async function safeWrite(action,payload,description){if(!navigator.onLine){const q=readQueue();q.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),action,payload,description,time:Date.now()});writeQueue(q);syncState(q.length+'건 오프라인 보관','error');toast('인터넷 연결 후 자동 저장됩니다.');return{queued:true}}syncState('저장 중','saving');try{const data=await api(action,payload);syncState('저장됨','');return data}catch(e){if(/세션|로그인/.test(e.message)){localStorage.removeItem(APP.tokenKey);ensureConnected()}throw e}}
async function flushQueue(manual=false){const q=readQueue();if(!q.length){if(manual)toast('미전송 작업이 없습니다.');return}if(!navigator.onLine){syncState(q.length+'건 오프라인 보관','error');return}syncState(q.length+'건 재전송','saving');const remain=[];for(const item of q){try{await api(item.action,item.payload)}catch(e){remain.push(item);if(/세션|로그인/.test(e.message))break}}writeQueue(remain);syncState(remain.length?remain.length+'건 재시도 필요':'저장됨',remain.length?'error':'');toast(remain.length?'일부 작업이 남았습니다.':'미전송 작업을 저장했습니다.');if(!remain.length)await refreshCurrent(true)}
function switchTab(tab){APP.tab=tab;document.querySelectorAll('.tab-panel').forEach(e=>e.classList.toggle('active',e.id==='tab-'+tab));document.querySelectorAll('.bottom-nav button').forEach(e=>e.classList.toggle('active',e.dataset.tab===tab));if(tab==='home')loadHome();if(tab==='retest')loadRetests();if(tab==='score')loadScores();if(tab==='absence')loadAbsences();if(tab==='notice')loadNotices()}
async function refreshCurrent(force=true){APP.loaded[APP.tab]=false;if(APP.tab==='home')return loadHome(force);if(APP.tab==='retest')return loadRetests(force);if(APP.tab==='score')return loadScores(force);if(APP.tab==='absence')return loadAbsences(force);if(APP.tab==='notice')return loadNotices(force)}
async function forceRefresh(){closeSettings();APP.loaded={};await refreshCurrent(true)}
function sectionTitle(title,sub,action=''){return `<div class="section-title"><div><h2>${esc(title)}</h2><p>${esc(sub||'')}</p></div>${action}</div>`}
function formatScore(v){if(v===''||v===null||v===undefined)return'';const n=Number(v);return Number.isFinite(n)?String(n):String(v)}

async function loadHome(force=false){if(!ensureConnected())return;const target=$('tab-home');const cached=readCache('home',600000);if(cached&&!APP.loaded.home){APP.data.home=cached;renderHome(cached)}if(APP.loaded.home&&!force)return;syncState('홈 확인 중','saving');try{const data=await api('quickHome',{force});APP.data.home=data;APP.loaded.home=true;writeCache('home',data);renderHome(data);syncState('최신','');$('header-sub').textContent=data.today+' · PWA v'+APP.version}catch(e){target.innerHTML=`<div class="banner error"><b>불러오기 실패</b><span>${esc(e.message)}</span></div>`;syncState('오류','error')}}
function renderHome(d){const c=d.counts||{},exam=d.examPeriod||{},actions=d.recentActions||[],auto=d.automation||[],mode=localStorage.getItem(APP.examModeKey)||'AUTO',examActive=mode==='ON'||(mode==='AUTO'&&exam.active);$('tab-home').innerHTML=`${sectionTitle('오늘의 운영','모바일에서 자주 쓰는 작업만 빠르게 처리합니다.','<button class="btn secondary small" onclick="loadHome(true)">새로고침</button>')}
${examActive?`<div class="banner warn"><b>시험기간 모드 · ${esc((exam.exam||{}).name||'최근 시험')}</b><span>학교시험 미입력 ${c.schoolScoreMissing||0}명 · 임시보관 ${c.scoreDrafts||0}건</span><div class="item-actions"><button class="btn primary small" onclick="switchTab('score')">점수 빠른입력</button></div></div>`:''}
<div class="grid metrics"><div class="metric ${c.openRetests?'attention':''}" onclick="switchTab('retest')"><span>재시험 대기</span><b>${c.openRetests||0}</b></div><div class="metric" onclick="openWritingOnly()"><span>단어쓰기 진행</span><b>${c.writing||0}</b></div><div class="metric ${c.schoolScoreMissing?'attention':''}" onclick="switchTab('score')"><span>학교시험 미입력</span><b>${c.schoolScoreMissing||0}</b></div><div class="metric" onclick="switchTab('absence')"><span>예정결석</span><b>${c.plannedAbsences||0}</b></div><div class="metric" onclick="switchTab('notice')"><span>게시 공지</span><b>${c.notices||0}</b></div></div>
<div class="card"><div class="item-head"><div><h3>빠른 실행</h3><p>자주 쓰는 기능으로 바로 이동합니다.</p></div></div><div class="item-actions"><a class="btn primary small link-btn" href="../recording/">녹음 확인</a><button class="btn secondary small" onclick="switchTab('score')">점수 입력</button><button class="btn secondary small" onclick="newAbsence()">예정결석 등록</button><button class="btn secondary small" onclick="newNotice()">공지 등록</button></div></div>
<div class="card"><div class="item-head"><div><h3>최근 처리</h3><p>잘못 처리한 작업은 바로 복원할 수 있습니다.</p></div></div>${actions.length?actions.map(a=>`<div class="recent-row"><div><b>${esc(a.message)}</b><small>${esc(a.createdAt)}</small></div>${a.status==='SUCCESS'?`<button class="btn secondary small" onclick="undoLog('${esc(a.logId)}')">되돌리기</button>`:`<span class="tag">복원됨</span>`}</div>`).join(''):'<div class="empty">최근 모바일 처리가 없습니다.</div>'}</div>
<div class="card"><div class="item-head"><div><h3>자동화 상태</h3><p>녹음 공지 자동 게시·종료 상태입니다.</p></div></div>${auto.length?auto.map(a=>`<div class="recent-row"><div><b><span class="status-dot ${a.status==='OK'?'':'bad'}"></span>${esc(a.category||a.key)}</b><small>${esc(a.finishedAt||'-')}</small></div><span class="tag ${a.status==='OK'?'':'red'}">${esc(a.status)}</span></div>`).join(''):'<div class="empty">기록이 없습니다.</div>'}</div>`}
async function undoLog(id){APP.lastLog=id;await undoLastAction()}
function openWritingOnly(){switchTab('retest');setTimeout(()=>{const s=$('retest-status');if(s){s.value='WRITING';loadRetests(true)}},50)}

async function loadRetests(force=false){if(!ensureConnected())return;if(APP.loaded.retest&&!force)return;const q=val('retest-query'),status=val('retest-status')||'OPEN';$('tab-retest').innerHTML=`${sectionTitle('단어 재시험','미응시·불합격은 자동으로 남아 다음 수업에도 표시됩니다.')}<div class="card"><div class="search-row"><input id="retest-query" placeholder="학생·반·단어장 검색" value="${esc(q)}"><select id="retest-status"><option value="OPEN" ${status==='OPEN'?'selected':''}>일반 재시험</option><option value="WRITING" ${status==='WRITING'?'selected':''}>단어쓰기 진행</option></select><button class="btn primary" onclick="loadRetests(true)">검색</button></div><div id="retest-list"><div class="empty">불러오는 중</div></div></div>`;syncState('재시험 확인 중','saving');try{const data=await api('quickRetests',{query:q,status});APP.data.retests=data;APP.loaded.retest=true;renderRetests(data);syncState('최신','')}catch(e){$('retest-list').innerHTML=`<div class="banner error">${esc(e.message)}</div>`;syncState('오류','error')}}
function renderRetests(data){const list=$('retest-list');list.innerHTML=(data.rows||[]).map(r=>`<div class="item"><div class="item-head"><div><h3>${esc(r.studentName)} <span class="tag ${r.status==='WRITING'?'amber':''}">${r.status==='WRITING'?'단어쓰기':'재시험'}</span></h3><p>${esc(r.className)} · ${esc(r.bookName||'단어장 미확인')} · ${esc(r.scope||'-')}</p><span class="meta">원시험 ${esc(r.originalDate||'-')} · 오답 ${r.wrongCount||0}개</span></div></div><div class="item-actions">${r.status==='WRITING'?`<button class="btn primary small" onclick="retestAction('${esc(r.retestId)}','WRITING_DONE',${r.recordVersion},'${esc(r.studentName)}')">단어쓰기 완료</button><button class="btn secondary small" onclick="retestAction('${esc(r.retestId)}','REOPEN',${r.recordVersion},'${esc(r.studentName)}')">재시험으로 복원</button>`:`<button class="btn primary small" onclick="retestAction('${esc(r.retestId)}','PASS',${r.recordVersion},'${esc(r.studentName)}')">통과 처리</button><button class="btn secondary small" onclick="retestAction('${esc(r.retestId)}','WRITING',${r.recordVersion},'${esc(r.studentName)}')">단어쓰기 전환</button>`}</div></div>`).join('')||'<div class="empty">처리할 재시험이 없습니다.</div>'}
async function retestAction(id,action,version,name){const label={PASS:'통과 처리',WRITING:'단어쓰기 전환',WRITING_DONE:'단어쓰기 완료',REOPEN:'재시험 복원'}[action];if(!confirm(`${name} 학생을 ${label}할까요?`))return;try{const result=await safeWrite('quickRetestAction',{retestId:id,action,recordVersion:version},label);if(!result.queued){showUndo(`${name} · ${label}`,result.logId);toast(label+'했습니다.');APP.loaded.retest=false;await loadRetests(true);await loadHome(true)}}catch(e){toast(e.message)}}

function recentStudents(){try{return JSON.parse(localStorage.getItem(APP.recentKey)||'[]')}catch(e){return[]}}function rememberStudent(s){if(!s||!s.studentId)return;const rows=[s,...recentStudents().filter(x=>x.studentId!==s.studentId)].slice(0,6);localStorage.setItem(APP.recentKey,JSON.stringify(rows))}
let SCORE_MODE='student';
async function loadScores(force=false){if(!ensureConnected())return;if(APP.loaded.score&&!force)return;APP.loaded.score=true;renderScoreShell();if(SCORE_MODE==='exam')await loadExamList();if(SCORE_MODE==='draft')await loadDrafts()}
function renderScoreShell(){const t=$('tab-score');t.innerHTML=`${sectionTitle('학교시험 점수','가장 최근 시험을 자동 선택하며, 완료된 점수는 수정 버튼을 눌러야 바뀝니다.')}<div class="subtabs"><button class="${SCORE_MODE==='student'?'active':''}" onclick="scoreSubtab('student')">학생 찾아 입력</button><button class="${SCORE_MODE==='exam'?'active':''}" onclick="scoreSubtab('exam')">시험별 연속입력</button><button class="${SCORE_MODE==='paste'?'active':''}" onclick="scoreSubtab('paste')">문자 붙여넣기</button><button class="${SCORE_MODE==='draft'?'active':''}" onclick="scoreSubtab('draft')">임시보관</button></div><div id="score-content"></div>`;if(SCORE_MODE==='student')renderStudentScoreSearch();if(SCORE_MODE==='paste')renderPasteScore()}
function scoreSubtab(mode){SCORE_MODE=mode;renderScoreShell();if(mode==='exam')loadExamList();if(mode==='draft')loadDrafts()}
function renderStudentScoreSearch(){const recent=recentStudents();$('score-content').innerHTML=`<div class="card"><div class="search-row"><input id="score-student-query" placeholder="학생 이름·반·학교"><button class="btn primary" onclick="searchScoreStudents()">검색</button></div>${recent.length?`<div class="subtabs">${recent.map(s=>`<button onclick="openStudentScore('${esc(s.studentId)}')">${esc(s.name)}</button>`).join('')}</div>`:''}<div id="score-student-results" class="list"><div class="empty">학생을 검색하세요.</div></div></div>`}
async function searchScoreStudents(){const q=val('score-student-query').trim();if(!q)return toast('학생 이름을 입력하세요.');syncState('학생 검색 중','saving');try{const data=await api('quickStudentSearch',{query:q});APP.data.studentSearch=data.rows||[];$('score-student-results').innerHTML=(data.rows||[]).map(s=>`<button class="item" style="text-align:left" onclick="openStudentScore('${esc(s.studentId)}')"><div class="item-head"><div><h3>${esc(s.name)}</h3><p>${esc(s.className)} · ${esc(s.schoolName)} ${s.grade?s.grade+'학년':''}</p></div><span class="tag">선택</span></div></button>`).join('')||'<div class="empty">학생을 찾지 못했습니다.</div>';syncState('최신','')}catch(e){toast(e.message)}}
async function openStudentScore(studentId){const found=(APP.data.studentSearch||[]).find(x=>x.studentId===studentId)||recentStudents().find(x=>x.studentId===studentId);if(found)rememberStudent(found);syncState('시험 확인 중','saving');try{const d=await api('quickStudentScoreContext',{studentId});const s=d.student,c=d.context;if(!c){openScoreEditor(s,null);return}openScoreEditor(s,c)}catch(e){toast(e.message)}finally{syncState('최신','')}}
function openScoreEditor(s,c){const existing=c&&c.existing,readonly=Boolean(existing);openModal(s.name,'학교시험 점수 빠른입력',`<div class="banner ${c?'':'warn'}"><b>${c?esc(c.examName):'등록된 시험을 찾지 못했습니다.'}</b><span>${c?esc(c.startDate)+' · 가장 최근 시험 자동 선택':'점수는 임시보관하고 나중에 정식 시험에 연결합니다.'}</span></div><div class="field-grid"><div><label>상태<select id="score-mode" onchange="toggleScoreField()"><option value="SCORE">점수 입력</option><option value="ABSENT" ${existing&&existing.absent?'selected':''}>결시</option><option value="NOSHOW">미응시</option><option value="REVIEW">확인 중</option></select></label></div><div><label>점수<input id="score-value" inputmode="decimal" placeholder="예: 92.75" value="${existing&&!existing.absent?esc(formatScore(existing.rawScore)):''}" ${readonly?'disabled':''}></label></div><div class="full"><label>메모<input id="score-memo" value="${existing?esc(existing.memo||''):''}" ${readonly?'disabled':''}></label></div>${!c?'<div class="full"><label>시험 메모<input id="score-exam-memo" placeholder="예: 1학기 기말고사"></label></div>':''}</div>${existing?`<div class="banner"><b>입력 완료 · ${existing.absent?'결시':esc(formatScore(existing.rawScore))+'점'}</b><span>수정 버튼을 눌러야 변경할 수 있습니다.</span></div><button id="score-edit-btn" class="btn secondary full" onclick="enableScoreEdit()">수정</button>`:''}<button id="score-save-btn" class="btn primary full" ${readonly?'disabled':''} onclick="saveStudentScore('${esc(s.studentId)}','${esc(c?c.examId:'')}',${existing?existing.recordVersion:0},${readonly})">${c?'저장':'임시보관'}</button>`);toggleScoreField()}
function enableScoreEdit(){$('score-value').disabled=false;$('score-memo').disabled=false;$('score-save-btn').disabled=false;$('score-edit-btn').disabled=true;$('score-save-btn').dataset.allowEdit='Y'}
function toggleScoreField(){const mode=val('score-mode'),input=$('score-value');if(input)input.disabled=mode!=='SCORE'||($('score-save-btn')&&$('score-save-btn').disabled);if(mode!=='SCORE'&&input)input.value=''}
async function saveStudentScore(studentId,examId,version,wasExisting){const mode=val('score-mode'),rawScore=val('score-value'),allowEdit=$('score-save-btn').dataset.allowEdit==='Y';if(mode==='SCORE'&&!/^\d{1,3}(?:\.\d{1,2})?$/.test(rawScore))return toast('소수점 둘째 자리까지 입력하세요.');try{const result=await safeWrite('quickSaveScore',{studentId,examId,mode,rawScore,memo:val('score-memo'),examMemo:val('score-exam-memo'),allowEdit,expectedScoreVersion:wasExisting?version:undefined},'점수 저장');if(!result.queued){closeModal();showUndo('학교시험 점수 저장',result.logId);toast(result.temporary?'임시보관했습니다.':'점수를 저장했습니다.');APP.loaded.home=false;await loadHome(true)}}catch(e){toast(e.message)}}
async function loadExamList(){const box=$('score-content');box.innerHTML='<div class="empty">시험 목록을 불러오는 중</div>';try{const d=await api('quickExamList');box.innerHTML=(d.rows||[]).map(e=>`<button class="item" style="text-align:left" onclick="openExamRoster('${esc(e.examId)}')"><div class="item-head"><div><h3>${esc(e.name)}</h3><p>${esc(e.startDate)} · ${esc(e.inputStatus||'-')}</p></div><span class="tag ${e.completed<e.total?'red':''}">${e.completed}/${e.total}</span></div></button>`).join('')||'<div class="empty">등록된 시험이 없습니다.</div>'}catch(e){box.innerHTML=`<div class="banner error">${esc(e.message)}</div>`}}
async function openExamRoster(examId){syncState('대상자 확인 중','saving');try{const d=await api('quickExamRoster',{examId});openModal(d.exam.name,'시험별 연속입력',`<div class="banner"><b>${esc(d.exam.startDate)}</b><span>입력 후 아래의 변경사항 저장을 누르세요.</span></div><div id="roster-list" class="list">${d.rows.map((r,i)=>`<div class="item"><div class="item-head"><div><h3>${esc(r.name)}</h3><p>${esc(r.className)}</p></div>${r.existing?'<span class="tag">입력 완료</span>':''}</div><div class="score-input"><select id="rmode-${i}" onchange="rosterMode(${i})"><option value="SCORE">점수</option><option value="ABSENT" ${r.targetStatus==='ABSENT'?'selected':''}>결시</option><option value="NOSHOW">미응시</option><option value="REVIEW">확인 중</option></select><input id="rscore-${i}" data-existing="${r.existing?'Y':'N'}" inputmode="decimal" value="${esc(formatScore(r.rawScore))}" placeholder="점수" ${r.existing?'disabled':''}><button id="redit-${i}" class="btn secondary small" onclick="enableRosterEdit(${i})" ${r.existing?'':'style="display:none"'}>수정</button></div><input type="hidden" id="rstudent-${i}" value="${esc(r.studentId)}"><input type="hidden" id="rversion-${i}" value="${r.scoreRecordVersion}"></div>`).join('')}</div><button class="btn primary full" onclick="saveRoster('${esc(examId)}',${d.rows.length})">변경사항 저장</button>`);d.rows.forEach((_,i)=>rosterMode(i))}catch(e){toast(e.message)}finally{syncState('최신','')}}
function enableRosterEdit(i){$(`rscore-${i}`).disabled=false;$(`redit-${i}`).dataset.edit='Y';$(`redit-${i}`).textContent='수정 허용'}function rosterMode(i){const mode=val(`rmode-${i}`),score=$(`rscore-${i}`),edit=$(`redit-${i}`),locked=score&&score.dataset.existing==='Y'&&(!edit||edit.dataset.edit!=='Y');if(score)score.disabled=mode!=='SCORE'||locked}
async function saveRoster(examId,count){const rows=[];for(let i=0;i<count;i++){const score=$(`rscore-${i}`),mode=val(`rmode-${i}`),edit=$(`redit-${i}`)&&$(`redit-${i}`).dataset.edit==='Y';if(mode==='SCORE'&&!score.value.trim())continue;if(score.disabled&&mode==='SCORE')continue;rows.push({studentId:val(`rstudent-${i}`),examId,mode,rawScore:score.value,allowEdit:edit,expectedScoreVersion:Number(val(`rversion-${i}`)||0)})}if(!rows.length)return toast('변경할 점수가 없습니다.');try{const d=await safeWrite('quickBatchSaveScores',{rows},'점수 일괄 저장');if(!d.queued){toast(`${d.saved}명 저장했습니다.${d.errors.length?' 오류 '+d.errors.length+'건':''}`);closeModal();await loadExamList();await loadHome(true)}}catch(e){toast(e.message)}}
function renderPasteScore(){$('score-content').innerHTML=`<div class="card"><label>문자·카카오톡 내용 붙여넣기<textarea id="paste-score-text" placeholder="김이찬 영어 94.25\n박정훈 88.5\n정시후 결시"></textarea></label><button class="btn primary full" onclick="analyzePastedScores()">분석</button></div><div id="paste-results"></div>`}
async function analyzePastedScores(){const text=val('paste-score-text');if(!text.trim())return toast('내용을 붙여넣으세요.');syncState('분석 중','saving');try{const d=await api('quickAnalyzeScores',{text});APP.data.pasteRows=d.rows;$('paste-results').innerHTML=`<div class="card"><h3>분석 결과</h3><div class="list">${d.rows.map((r,i)=>`<div class="item"><div class="item-head"><div><h3>${esc(r.name||r.raw)}</h3><p>${r.matchStatus==='MATCHED'?esc(r.examName||'시험 미등록'):r.matchStatus==='DUPLICATE'?'동명이인 선택 필요':'학생을 찾지 못함'}</p></div><span class="tag ${r.matchStatus==='MATCHED'?'':'red'}">${r.mode==='SCORE'?esc(r.rawScore)+'점':esc(r.mode)}</span></div>${r.matchStatus==='DUPLICATE'?`<select onchange="selectPasteCandidate(${i},this.value)"><option value="">학생 선택</option>${r.candidates.map(c=>`<option value="${esc(c.studentId)}">${esc(c.className)}</option>`).join('')}</select>`:''}${r.existing?`<label><input type="checkbox" id="paste-edit-${i}" style="width:auto"> 기존 점수 수정 허용</label>`:''}</div>`).join('')}</div><button class="btn primary full" onclick="savePastedScores()">확인된 항목 저장</button></div>`;syncState('최신','')}catch(e){toast(e.message)}}
async function selectPasteCandidate(index,studentId){if(!studentId)return;try{const d=await api('quickStudentScoreContext',{studentId});const r=APP.data.pasteRows[index];r.studentId=studentId;r.matchStatus='MATCHED';r.examId=d.context?d.context.examId:'';r.examName=d.context?d.context.examName:'';r.existing=Boolean(d.context&&d.context.existing);toast('학생을 선택했습니다. 다시 저장 버튼을 누르세요.')}catch(e){toast(e.message)}}
async function savePastedScores(){const rows=(APP.data.pasteRows||[]).map((r,i)=>({...r,_index:i})).filter(r=>r.matchStatus==='MATCHED').map(r=>({studentId:r.studentId,examId:r.examId,mode:r.mode,rawScore:r.rawScore,rawInput:r.raw,examMemo:r.examName?'':'문자 붙여넣기',allowEdit:r.existing&&$(`paste-edit-${r._index}`)&&$(`paste-edit-${r._index}`).checked,existing:r.existing})).filter(r=>!r.existing||r.allowEdit);if(!rows.length)return toast('저장 가능한 항목이 없습니다.');try{const d=await safeWrite('quickBatchSaveScores',{rows},'붙여넣기 점수 저장');if(!d.queued){toast(`${d.saved}명 저장했습니다.`);renderPasteScore();await loadHome(true)}}catch(e){toast(e.message)}}
async function loadDrafts(){const box=$('score-content');box.innerHTML='<div class="empty">임시 점수를 불러오는 중</div>';try{const d=await api('quickDrafts');box.innerHTML=(d.rows||[]).map(r=>`<div class="item"><div class="item-head"><div><h3>${esc(r.studentName)} · ${r.resultStatus==='SCORE'?esc(formatScore(r.rawScore))+'점':esc(r.resultStatus)}</h3><p>${esc(r.className)} · ${esc(r.examMemo||'시험 메모 없음')}</p></div><span class="tag amber">연결 필요</span></div><span class="meta">${esc(r.createdAt)}</span><div class="item-actions"><button class="btn primary small" onclick="linkDraft('${esc(r.draftId)}')">최근 시험에 연결</button></div></div>`).join('')||'<div class="empty">임시보관 점수가 없습니다.</div>'}catch(e){box.innerHTML=`<div class="banner error">${esc(e.message)}</div>`}}

async function linkDraft(draftId){if(!confirm('이 임시 점수를 현재 가장 최근 시험에 연결할까요?'))return;try{const r=await safeWrite('quickLinkDraft',{draftId},'임시 점수 연결');if(!r.queued){showUndo('임시 점수를 최근 시험에 연결',r.logId);toast('최근 시험에 연결했습니다.');await loadDrafts();await loadHome(true)}}catch(e){toast(e.message)}}

async function loadAbsences(force=false){if(!ensureConnected())return;if(APP.loaded.absence&&!force)return;$('tab-absence').innerHTML=`${sectionTitle('예정결석','예정결석이어도 단어녹음 제출 대상은 유지됩니다.','<button class="btn primary small" onclick="newAbsence()">등록</button>')}<div id="absence-list"><div class="empty">불러오는 중</div></div>`;try{const d=await api('quickAbsences');APP.data.absences=d;APP.loaded.absence=true;renderAbsences(d)}catch(e){$('absence-list').innerHTML=`<div class="banner error">${esc(e.message)}</div>`}}
function renderAbsences(d){$('absence-list').innerHTML=(d.rows||[]).map(r=>`<div class="item"><div class="item-head"><div><h3>${esc(r.studentName)}</h3><p>${esc(r.className)} · ${esc(r.startDate)}${r.endDate!==r.startDate?' ~ '+esc(r.endDate):''}</p><span class="meta">${esc(r.reason||'사유 없음')}</span></div></div><div class="item-actions"><button class="btn secondary small" onclick="editAbsence('${esc(r.plannedAbsenceId)}')">수정</button><button class="btn danger small" onclick="cancelAbsence('${esc(r.plannedAbsenceId)}','${esc(r.studentName)}')">취소</button></div></div>`).join('')||'<div class="empty">예정결석이 없습니다.</div>'}
function absenceOptions(selected=''){const students=(APP.data.absences||{}).students||[];return students.map(s=>`<option value="${esc(s.studentId)}" ${s.studentId===selected?'selected':''}>${esc(s.name)} · ${esc(s.className)}</option>`).join('')}
function newAbsence(){if(!APP.data.absences){switchTab('absence');setTimeout(newAbsence,600);return}openAbsenceForm(null)}function editAbsence(id){const row=(APP.data.absences.rows||[]).find(r=>r.plannedAbsenceId===id);if(row)openAbsenceForm(row)}
function openAbsenceForm(row){const start=row?row.startDate:currentDate(),end=row?row.endDate:start;openModal(row?'예정결석 수정':'예정결석 등록','출결',`<div class="banner"><b>녹음 제출 대상 유지</b><span>예정결석을 등록해도 해당 단어시험 녹음은 제출해야 합니다.</span></div><div class="field-grid"><div class="full"><label>학생<select id="absence-student"><option value="">선택</option>${absenceOptions(row&&row.studentId)}</select></label></div><div><label>시작일<input id="absence-start" type="date" value="${esc(start)}"></label></div><div><label>종료일<input id="absence-end" type="date" value="${esc(end)}"></label></div><div class="full actions"><button class="btn secondary small" onclick="setAbsenceDate('today')">오늘</button><button class="btn secondary small" onclick="setAbsenceDate('tomorrow')">내일</button><button class="btn secondary small" onclick="setAbsenceDate('next')">다음 수업</button></div><div class="full"><label>사유<input id="absence-reason" value="${esc(row&&row.reason||'')}"></label></div></div><button class="btn primary full" onclick="saveAbsence('${esc(row&&row.plannedAbsenceId||'')}',${row?row.recordVersion:0})">저장</button>`)}
async function setAbsenceDate(kind){let d=currentDate();if(kind==='tomorrow')d=addDays(d,1);if(kind==='next'){const studentId=val('absence-student');if(!studentId)return toast('학생을 먼저 선택하세요.');try{const r=await api('quickNextClassDate',{studentId,afterDate:currentDate()});if(!r.date)return toast('다음 수업일을 찾지 못했습니다.');d=r.date}catch(e){return toast(e.message)}}$('absence-start').value=d;$('absence-end').value=d}
async function saveAbsence(id,version){const studentId=val('absence-student'),startDate=val('absence-start'),endDate=val('absence-end'),reason=val('absence-reason');if(!studentId||!startDate||!endDate)return toast('학생과 날짜를 입력하세요.');try{const r=await safeWrite('quickSaveAbsence',{plannedAbsenceId:id,recordVersion:version||undefined,studentId,startDate,endDate,reason},'예정결석 저장');if(!r.queued){closeModal();showUndo('예정결석 저장',r.logId);toast('예정결석을 저장했습니다.');APP.loaded.absence=false;await loadAbsences(true);await loadHome(true)}}catch(e){toast(e.message)}}
async function cancelAbsence(id,name){if(!confirm(`${name} 학생의 예정결석을 취소할까요?`))return;try{const r=await safeWrite('quickCancelAbsence',{plannedAbsenceId:id},'예정결석 취소');if(!r.queued){showUndo(`${name} 예정결석 취소`,r.logId);APP.loaded.absence=false;await loadAbsences(true);await loadHome(true)}}catch(e){toast(e.message)}}

async function loadNotices(force=false){if(!ensureConnected())return;if(APP.loaded.notice&&!force)return;$('tab-notice').innerHTML=`${sectionTitle('공지 관리','확인·등록·수정·보관과 학생앱 미리보기를 지원합니다.','<button class="btn primary small" onclick="newNotice()">새 공지</button>')}<div id="notice-list"><div class="empty">불러오는 중</div></div>`;try{const d=await api('quickContents');APP.data.notices=d;APP.loaded.notice=true;renderNotices(d)}catch(e){$('notice-list').innerHTML=`<div class="banner error">${esc(e.message)}</div>`}}
function renderNotices(d){$('notice-list').innerHTML=(d.rows||[]).map(r=>`<div class="item"><div class="item-head"><div><h3>${esc(r.title||'제목 없음')} ${r.automatic?'<span class="tag amber">자동 공지</span>':''}</h3><p>${esc(r.body.slice(0,100))}${r.body.length>100?'…':''}</p><span class="meta">${esc(r.status)} · ${esc(r.targetSummary||'전체')} · ${esc(r.updatedAt)}</span></div></div><div class="item-actions"><button class="btn secondary small" onclick="previewNotice('${esc(r.contentId)}')">미리보기</button>${r.automatic?`${r.status==='PUBLISHED'?`<button class="btn secondary small" onclick="setNoticeStatus('${esc(r.contentId)}','hide')">숨김</button>`:`<button class="btn primary small" onclick="setNoticeStatus('${esc(r.contentId)}','restore')">다시 게시</button>`}`:`<button class="btn secondary small" onclick="editNotice('${esc(r.contentId)}')">수정</button>${r.status==='ARCHIVED'?`<button class="btn primary small" onclick="setNoticeStatus('${esc(r.contentId)}','restore')">보관 취소</button>`:`<button class="btn danger small" onclick="setNoticeStatus('${esc(r.contentId)}','archive')">보관</button>`}`}</div></div>`).join('')||'<div class="empty">공지가 없습니다.</div>'}
function newNotice(){if(!APP.data.notices){switchTab('notice');setTimeout(newNotice,600);return}openNoticeForm(null)}function editNotice(id){const r=(APP.data.notices.rows||[]).find(x=>x.contentId===id);if(r)openNoticeForm(r)}
function noticeClassOptions(selected=''){return ((APP.data.notices||{}).classes||[]).map(c=>`<option value="${esc(c.classId)}" ${selected===c.classId?'selected':''}>${esc(c.className)}</option>`).join('')}
function openNoticeForm(r){const target=(r&&r.targets&&r.targets[0])||{},scope=target.type==='CLASS'?'CLASS':target.type==='COURSE'?'COURSE':'ALL';openModal(r?'공지 수정':'새 공지','학생앱 공지',`<div class="field-grid"><div><label>상태<select id="notice-status"><option value="PUBLISHED" ${!r||r.status==='PUBLISHED'?'selected':''}>즉시 게시</option><option value="DRAFT" ${r&&r.status==='DRAFT'?'selected':''}>임시저장</option><option value="HIDDEN" ${r&&r.status==='HIDDEN'?'selected':''}>숨김</option></select></label></div><div><label>공개 대상<select id="notice-scope" onchange="noticeScopeChanged()"><option value="ALL" ${scope==='ALL'?'selected':''}>전체</option><option value="COURSE" ${scope==='COURSE'?'selected':''}>과정</option><option value="CLASS" ${scope==='CLASS'?'selected':''}>특정 반</option></select></label></div><div id="notice-target-wrap"><label>대상<select id="notice-target"><option value="초" ${target.value==='초'?'selected':''}>초등부</option><option value="중" ${target.value==='중'?'selected':''}>중등부</option><option value="고" ${target.value==='고'?'selected':''}>고등부</option>${noticeClassOptions(target.value)}</select></label></div><div class="full"><label>제목<input id="notice-title" value="${esc(r&&r.title||'')}"></label></div><div class="full"><label>내용<textarea id="notice-body">${esc(r&&r.body||'')}</textarea></label></div><div><label>게시 시작<input id="notice-start" type="datetime-local" value="${esc((r&&r.startAt||'').replace(' ','T').slice(0,16))}"></label></div><div><label>게시 종료<input id="notice-end" type="datetime-local" value="${esc((r&&r.endAt||'').replace(' ','T').slice(0,16))}"></label></div></div><button class="btn secondary full" onclick="previewNoticeForm()">학생앱 미리보기</button><button class="btn primary full" onclick="saveNotice('${esc(r&&r.contentId||'')}',${r?r.recordVersion:0})">저장</button>`);noticeScopeChanged(target.value||'')}
function noticeScopeChanged(selected=''){const scope=val('notice-scope'),wrap=$('notice-target-wrap');if(!wrap)return;wrap.style.display=scope==='ALL'?'none':'block';const select=$('notice-target');if(scope==='COURSE')select.innerHTML='<option value="초">초등부</option><option value="중">중등부</option><option value="고">고등부</option>';if(scope==='CLASS')select.innerHTML=noticeClassOptions(selected);if(selected)select.value=selected}
function previewNoticeForm(){const title=val('notice-title')||'제목 없음',body=val('notice-body')||'내용 없음';alert(title+'\n\n'+body)}
function previewNotice(id){const r=(APP.data.notices.rows||[]).find(x=>x.contentId===id);if(!r)return;openModal('학생앱 미리보기',r.automatic?'자동 공지':'공지',`<div class="preview"><b>${esc(r.title)}</b>\n\n${esc(r.body)}</div><button class="btn primary full" onclick="closeModal()">확인</button>`)}
async function saveNotice(id,version){const scope=val('notice-scope'),target=val('notice-target'),targets=scope==='ALL'?[]:[{type:scope,value:target}],summary=scope==='ALL'?'전체 공개':scope==='COURSE'?target+'등부':((APP.data.notices.classes||[]).find(c=>c.classId===target)||{}).className||'특정 반';try{const r=await safeWrite('quickSaveContent',{contentId:id,recordVersion:version||undefined,status:val('notice-status'),title:val('notice-title'),body:val('notice-body'),startAt:val('notice-start'),endAt:val('notice-end'),targets,targetSummary:summary},'공지 저장');if(!r.queued){closeModal();showUndo('공지 저장',r.logId);APP.loaded.notice=false;await loadNotices(true);await loadHome(true)}}catch(e){toast(e.message)}}
async function setNoticeStatus(id,action){const msg={archive:'보관',restore:'다시 게시',hide:'숨김'}[action];if(!confirm(`이 공지를 ${msg}할까요?`))return;const apiAction={archive:'quickArchiveContent',restore:'quickRestoreContent',hide:'quickHideContent'}[action];try{const r=await safeWrite(apiAction,{contentId:id},'공지 '+msg);if(!r.queued){showUndo('공지 '+msg,r.logId);APP.loaded.notice=false;await loadNotices(true);await loadHome(true)}}catch(e){toast(e.message)}}

function bindDateRanges(){const pairs=[['absence-start','absence-end'],['notice-start','notice-end']];pairs.forEach(([a,b])=>{const s=$(a),e=$(b);if(!s||!e||s.dataset.rangeBound)return;s.dataset.rangeBound='1';s.addEventListener('change',()=>{if(!e.value||e.value<s.value)e.value=s.value});e.addEventListener('change',()=>{if(s.value&&e.value<s.value){e.value=s.value;toast('종료일을 시작일과 같은 날로 조정했습니다.')}})})}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();APP.installPrompt=e;if(localStorage.getItem('allbarun.quick.installDismissed')!=='Y')$('install-banner').classList.remove('hidden')});
async function installApp(){if(!APP.installPrompt)return toast('브라우저 메뉴에서 홈 화면에 추가하세요.');APP.installPrompt.prompt();await APP.installPrompt.userChoice;APP.installPrompt=null;$('install-banner').classList.add('hidden')}
function dismissInstall(){localStorage.setItem('allbarun.quick.installDismissed','Y');$('install-banner').classList.add('hidden')}
window.addEventListener('beforeunload',e=>{if(readQueue().length){e.preventDefault();e.returnValue='';}});window.addEventListener('online',()=>{updateNetwork();flushQueue(false)});window.addEventListener('offline',updateNetwork);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-(APP.lastVisible||0)>300000)refreshCurrent(false);APP.lastVisible=Date.now()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updateNetwork();if(ensureConnected()){loadHome();flushQueue(false)}
