const APP={version:'7.5.0',apiKey:'allbarun.rec.apiUrl',tokenKey:'allbarun.rec.token',targetDate:'',data:null,loading:false,saving:new Set(),lastLoaded:0};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function syncState(text,kind=''){const el=$('sync-state');el.textContent=text;el.className='pill '+kind}
function apiUrl(){return localStorage.getItem(APP.apiKey)||''}function token(){return localStorage.getItem(APP.tokenKey)||''}
async function api(action,payload={},override={}){const url=override.url||apiUrl();if(!url)throw new Error('서버 주소가 설정되지 않았습니다.');const body={action,payload,token:override.token===undefined?token():override.token,pin:override.pin||''};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const res=await fetch(url,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),signal:controller.signal});const text=await res.text();let json;try{json=JSON.parse(text)}catch(e){throw new Error('서버 응답을 읽지 못했습니다. 배포 주소와 권한을 확인하세요.')}if(!json.success)throw new Error(json.error&&json.error.message||'요청 실패');return json.data}catch(e){if(e&&e.name==='AbortError')throw new Error('서버 응답이 45초 이상 지연되었습니다. 전용 시트에서 체크값을 확인하세요.');throw e}finally{clearTimeout(timer)}}
function updateNetwork(){const online=navigator.onLine;const el=$('network-state');el.textContent=online?'온라인':'오프라인';el.className='pill '+(online?'':'offline')}
async function connectServer(){const url=$('api-url').value.trim(),pin=$('admin-pin').value.trim();if(!url||!pin){toast('주소와 PIN을 입력하세요.');return}syncState('연결 중','saving');try{const login=await api('login',{}, {url,pin,token:''});localStorage.setItem(APP.apiKey,url);localStorage.setItem(APP.tokenKey,login.token);$('setup-modal').classList.remove('show');toast('연결했습니다.');await loadData(true)}catch(e){syncState('연결 오류','error');toast(e.message)}}
function ensureConnected(){if(!apiUrl()||!token()){$('api-url').value=apiUrl();$('setup-modal').classList.add('show');return false}$('setup-modal').classList.remove('show');return true}
function closeSetupIfConnected(){if(apiUrl()&&token())$('setup-modal').classList.remove('show')}
function openConnectionSettings(){closeSettings();$('api-url').value=apiUrl();$('admin-pin').value='';$('setup-modal').classList.add('show')}
function openSettings(){$('settings-modal').classList.add('show')}function closeSettings(){$('settings-modal').classList.remove('show')}
async function loadData(force=false){if(!ensureConnected()||APP.loading)return;APP.loading=true;syncState('시트 확인 중','saving');try{const d=await api('sheetDashboard',{targetDate:APP.targetDate,force});APP.data=d;APP.targetDate=d.targetDate;APP.lastLoaded=Date.now();render(d);syncState('최신','');}catch(e){$('banner').className='banner error';$('banner').innerHTML='<b>불러오기 실패</b><span>'+esc(e.message)+'</span>';syncState('오류','error');}finally{APP.loading=false}}
function render(d){$('now-label').textContent=d.targetLabel+' · 시트 우선 PWA v'+APP.version;$('m-total').textContent=d.totalStudents;$('m-received').textContent=d.totalReceived;$('m-missing').textContent=d.totalMissing;const b=$('banner');b.className='banner';b.innerHTML='<b>'+esc(d.targetLabel)+' · '+esc((d.batch&&d.batch.status)||'')+'</b><span>전용 시트 `녹음체크_운영` 기준입니다. 체크 저장 성공 후 공지도 즉시 갱신됩니다.</span>';$('classes').innerHTML=(d.classes||[]).map(renderClass).join('')||'<div class="empty">표시할 대상이 없습니다. 시트 재생성을 눌러주세요.</div>'}
function renderClass(c){return `<section class="class-card" data-class="${esc(c.classId)}"><div class="class-head"><div><h2>${esc(c.className)}</h2><p>${esc(c.vocabSummary||'단어범위 확인 필요')}</p></div><div class="count">${c.receivedCount}/${c.students.length} 제출</div></div><div class="student-list">${c.students.map(s=>renderStudent(c,s)).join('')}</div></section>`}
function renderStudent(c,s){const key=esc(s.classId+'|'+s.studentId);const checked=s.submitted?'checked':'';const state=s.submitted?'녹음 제출':(s.serverStatus==='MISSING'?'녹음X':'미확인');return `<label class="student ${s.submitted?'':'missing'}" data-key="${key}"><input type="checkbox" ${checked} onchange="saveOne(this,'${esc(s.classId)}','${esc(s.studentId)}')"><div><span class="name">${esc(s.name)}</span><span class="state">${esc(state)}${s.savedAt?' · '+esc(s.savedAt):''}</span></div></label>`}
function findStudent(classId,studentId){for(const c of (APP.data&&APP.data.classes)||[]){if(c.classId===classId)return c.students.find(s=>s.studentId===studentId)}return null}
function recalc(){let total=0,received=0;(APP.data.classes||[]).forEach(c=>{c.receivedCount=c.students.filter(s=>s.submitted).length;total+=c.students.length;received+=c.receivedCount});APP.data.totalStudents=total;APP.data.totalReceived=received;APP.data.totalMissing=Math.max(0,total-received);$('m-total').textContent=total;$('m-received').textContent=received;$('m-missing').textContent=APP.data.totalMissing}
async function saveOne(input,classId,studentId){const k=classId+'|'+studentId;if(APP.saving.has(k)){input.checked=!input.checked;return}const desired=input.checked,student=findStudent(classId,studentId);if(!student){input.checked=!desired;return}APP.saving.add(k);input.disabled=true;const card=input.closest('.student'),state=card.querySelector('.state');card.classList.add('pending');state.textContent='저장 중...';syncState('1명 저장 중','saving');try{const r=await api('sheetSaveOne',{targetDate:APP.targetDate,classId,studentId,submitted:desired});student.submitted=desired;student.serverStatus=r.serverStatus;student.savedAt=r.savedAt;card.classList.toggle('missing',!desired);state.textContent=(desired?'녹음 제출':'미확인')+' · '+r.savedAt;recalc();syncState('저장됨','');toast('저장했습니다.')}catch(e){input.checked=!desired;card.classList.add('retry');state.textContent='저장 실패';syncState('오류','error');toast(e.message)}finally{card.classList.remove('pending');input.disabled=false;APP.saving.delete(k)}}
async function syncNotice(){if(!ensureConnected())return;syncState('공지 동기화 중','saving');try{const r=await api('sheetPublish',{targetDate:APP.targetDate});toast('공지 동기화 완료 · '+r.synced+'명');await loadData(true)}catch(e){syncState('오류','error');toast(e.message)}}
async function refreshSheet(){if(!confirm('현재 날짜의 전용 시트를 서버 대상자 기준으로 다시 확인할까요? 기존 체크값은 보존됩니다.'))return;syncState('시트 재생성 중','saving');try{await api('sheetRefresh',{targetDate:APP.targetDate});toast('시트를 확인했습니다.');await loadData(true)}catch(e){syncState('오류','error');toast(e.message)}}
window.addEventListener('online',()=>{updateNetwork();loadData(false)});window.addEventListener('offline',updateNetwork);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-APP.lastLoaded>300000)loadData(false)});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updateNetwork();if(ensureConnected())loadData(false);