const APP={version:'7.4.0',apiKey:'allbarun.rec.apiUrl',tokenKey:'allbarun.rec.token',dataPrefix:'allbarun.rec.v740.data.',queueKey:'allbarun.rec.queue',targetDate:'',data:null,pending:new Map(),flushTimer:null,saving:false,lastLoaded:0,loadSeq:0};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1900)}
function syncState(text,kind=''){const el=$('sync-state');el.textContent=text;el.className='pill '+kind}
function apiUrl(){return localStorage.getItem(APP.apiKey)||''}function token(){return localStorage.getItem(APP.tokenKey)||''}
async function api(action,payload={},override={}){const url=override.url||apiUrl();if(!url)throw new Error('서버 주소가 설정되지 않았습니다.');const body={action,payload,token:override.token===undefined?token():override.token,pin:override.pin||''};const res=await fetch(url,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const text=await res.text();let json;try{json=JSON.parse(text)}catch(e){throw new Error('서버 응답을 읽지 못했습니다. 배포 권한과 주소를 확인하세요.')}if(!json.success)throw new Error(json.error&&json.error.message||'요청 실패');return json.data}
function dataKey(date){return APP.dataPrefix+(date||'default')}function readData(date){try{const x=JSON.parse(localStorage.getItem(dataKey(date))||'null');return x&&Date.now()-x.savedAt<24*3600000?x.data:null}catch(e){return null}}function writeData(data){try{localStorage.setItem(dataKey(data.targetDate),JSON.stringify({savedAt:Date.now(),data}));localStorage.setItem(dataKey('default'),JSON.stringify({savedAt:Date.now(),data}))}catch(e){}}
function readQueue(){try{return JSON.parse(localStorage.getItem(APP.queueKey)||'[]')}catch(e){return[]}}function writeQueue(rows){localStorage.setItem(APP.queueKey,JSON.stringify(rows))}function mergeQueue(changes,date){const map={};readQueue().forEach(x=>map[x.targetDate+'|'+x.classId+'|'+x.studentId]=x);changes.forEach(x=>map[date+'|'+x.classId+'|'+x.studentId]={...x,targetDate:date,queuedAt:Date.now()});writeQueue(Object.values(map));}
function updateNetwork(){const online=navigator.onLine;const el=$('network-state');el.textContent=online?'온라인':'오프라인';el.className='pill '+(online?'':'offline')}
async function connectServer(){const url=$('api-url').value.trim(),pin=$('admin-pin').value.trim();if(!url||!pin){toast('주소와 PIN을 입력하세요.');return}syncState('연결 중','saving');try{const login=await api('login',{}, {url,pin,token:''});localStorage.setItem(APP.apiKey,url);localStorage.setItem(APP.tokenKey,login.token);$('setup-modal').classList.remove('show');toast('연결했습니다.');await loadData('',true)}catch(e){syncState('연결 오류','error');toast(e.message)}}
function ensureConnected(){if(!apiUrl()||!token()){$('api-url').value=apiUrl();$('setup-modal').classList.add('show');return false}return true}function closeSetupIfConnected(){if(apiUrl()&&token())$('setup-modal').classList.remove('show')}function openConnectionSettings(){$('api-url').value=apiUrl();$('admin-pin').value='';$('setup-modal').classList.add('show')}
async function loadData(date='',force=false){if(!ensureConnected()||APP.saving)return;const requestId=++APP.loadSeq;const requested=date||APP.targetDate;const cached=readData(requested||'default');if(cached&&!APP.data&&(!requested||cached.targetDate===requested)){APP.data=cached;APP.targetDate=cached.targetDate;render(cached);syncState('저장된 화면','saving')}else syncState('확인 중','saving');if(!navigator.onLine){syncState('오프라인','error');return}try{const data=await api('dashboard',{targetDate:requested,force:Boolean(force)});if(requestId!==APP.loadSeq)return;APP.data=data;APP.targetDate=data.targetDate;APP.lastLoaded=Date.now();writeData(data);render(data);syncState('최신','')}catch(e){if(requestId!==APP.loadSeq)return;if(/세션|로그인/.test(e.message)){localStorage.removeItem(APP.tokenKey);ensureConnected()}$('banner').className='banner error';$('banner').innerHTML='<b>불러오기 실패</b>'+esc(e.message);syncState('오류','error')}}
function render(d){$('now-label').textContent=d.now+' · PWA v'+APP.version;$('m-total').textContent=d.totalStudents;$('m-received').textContent=d.totalReceived;$('m-missing').textContent=d.totalMissing;$('date-strip').innerHTML=(d.candidates||[]).map(x=>`<button class="datebtn ${x.date===d.targetDate?'active':''}" onclick="loadData('${x.date}')">${esc(x.label)}<small>${x.studentCount}명 · ${esc(x.status)}</small></button>`).join('');const b=$('banner'),pub=$('publish-btn');if(d.exemptReason){b.className='banner warn';b.innerHTML='<b>'+esc(d.targetLabel)+'</b>'+esc(d.exemptReason);pub.disabled=true}else if(d.batch.closed){b.className='banner';b.innerHTML='<b>'+esc(d.targetLabel)+' · 공지 종료</b>오후 3시에 공지만 내렸고 오늘수업 녹음X는 유지됩니다.';pub.disabled=true}else if(d.batch.published){b.className='banner';b.innerHTML='<b>'+esc(d.targetLabel)+' · 공지 게시 중</b>체크 즉시 화면에서 제거되고 묶음 저장됩니다.';pub.textContent='공지 게시 중';pub.disabled=true}else{b.className='banner warn';b.innerHTML='<b>'+esc(d.targetLabel)+' · 미리 체크 가능</b>미리 보낸 학생은 지금 체크해두세요.';pub.textContent='미제출 공지 지금 게시';pub.disabled=false}$('classes').innerHTML=(d.classes||[]).map(renderClass).join('')||'<div class="empty">표시할 녹음 대상이 없습니다.</div>'}
function renderClass(c){return `<section class="class-card" data-class="${esc(c.classId)}"><div class="class-head"><div><h2>${esc(c.className)}</h2><p>${esc(c.vocabSummary||'단어시험 범위 확인 필요')}</p></div><div class="count" data-class-count>${c.receivedCount}/${c.students.length} 제출</div></div><div class="student-list">${c.students.map(s=>`<label class="student ${s.status==='MISSING'?'missing':''}" data-key="${esc(c.classId+'|'+s.studentId)}"><input type="checkbox" ${s.received?'checked':''} onchange="toggleStudent(this,'${esc(c.classId)}','${esc(s.studentId)}')"><div><span class="name">${esc(s.name)}</span><span class="state">${s.status==='RECEIVED'?'녹음 제출':s.status==='UNKNOWN'?'미확인':'미제출'}</span></div></label>`).join('')}</div></section>`}
function findStudent(classId,studentId){const c=(APP.data.classes||[]).find(x=>x.classId===classId);return c&&c.students.find(x=>x.studentId===studentId)}
function recalc(){let total=0,received=0,missing=0;(APP.data.classes||[]).forEach(c=>{c.receivedCount=c.students.filter(s=>s.status==='RECEIVED').length;c.missingCount=c.students.filter(s=>s.status==='MISSING').length;total+=c.students.length;received+=c.receivedCount;missing+=c.missingCount;const el=document.querySelector(`[data-class="${CSS.escape(c.classId)}"] [data-class-count]`);if(el)el.textContent=`${c.receivedCount}/${c.students.length} 제출`});APP.data.totalStudents=total;APP.data.totalReceived=received;APP.data.totalMissing=missing;$('m-total').textContent=total;$('m-received').textContent=received;$('m-missing').textContent=missing;writeData(APP.data)}
function toggleStudent(input,classId,studentId){const student=findStudent(classId,studentId);if(!student)return;const published=Boolean(APP.data.batch&&APP.data.batch.published);student.received=input.checked;student.status=input.checked?'RECEIVED':(published?'MISSING':'UNKNOWN');const card=input.closest('.student');card.classList.toggle('missing',student.status==='MISSING');card.classList.add('pending');card.classList.remove('retry');card.querySelector('.state').textContent=student.status==='RECEIVED'?'녹음 제출':student.status==='UNKNOWN'?'미확인':'미제출';APP.pending.set(classId+'|'+studentId,{classId,studentId,received:input.checked});recalc();syncState('저장 대기','saving');clearTimeout(APP.flushTimer);APP.flushTimer=setTimeout(()=>flushPending(),500)}
async function flushPending(){if(APP.saving||!APP.pending.size)return;const items=[...APP.pending.values()];APP.pending.clear();mergeQueue(items,APP.targetDate);await flushQueue(false)}
async function flushQueue(manual=false){if(APP.saving)return;const queue=readQueue();if(!queue.length){if(manual)toast('미전송 항목이 없습니다.');return}if(!navigator.onLine){syncState(queue.length+'명 오프라인 보관','error');return}APP.saving=true;syncState(queue.length+'명 저장 중','saving');const grouped={};queue.forEach(x=>(grouped[x.targetDate]||(grouped[x.targetDate]=[])).push(x));try{for(const [date,rows] of Object.entries(grouped)){await api('saveChanges',{targetDate:date,changes:rows.map(({classId,studentId,received})=>({classId,studentId,received}))})}writeQueue([]);document.querySelectorAll('.student.pending,.student.retry').forEach(x=>x.classList.remove('pending','retry'));syncState('저장됨','');toast(queue.length+'명 저장 완료')}catch(e){document.querySelectorAll('.student.pending').forEach(x=>{x.classList.remove('pending');x.classList.add('retry')});syncState(queue.length+'명 재시도 필요','error');if(/세션|로그인/.test(e.message)){localStorage.removeItem(APP.tokenKey);ensureConnected()}toast(e.message)}finally{APP.saving=false;if(APP.pending.size)setTimeout(flushPending,150)}}
async function publishNow(){await flushPending();if(readQueue().length){toast('미전송 체크를 먼저 저장하세요.');return}if(!confirm(APP.targetDate+' 미체크 학생을 녹음 미제출로 전체 공개할까요?'))return;syncState('공지 게시 중','saving');try{await api('publishNow',{targetDate:APP.targetDate});toast('공지를 게시했습니다.');APP.data=null;await loadData(APP.targetDate,true)}catch(e){toast(e.message);syncState('오류','error')}}
async function openSettings(){$('settings-modal').classList.add('show');$('settings-list').innerHTML='<div class="empty">불러오는 중</div>';try{const rows=await api('classSettings');$('settings-list').innerHTML=rows.map(r=>`<div class="setting"><div><b>${esc(r.className)}</b><small>${esc(r.course||'-')} · ${esc(r.classType||'-')} · ${esc(r.source)}</small></div><button class="switch ${r.enabled?'on':''}" onclick="toggleSetting(this,'${esc(r.classId)}',${!r.enabled})"><span></span></button></div>`).join('')}catch(e){toast(e.message)}}function closeSettings(){$('settings-modal').classList.remove('show')}async function toggleSetting(btn,classId,enabled){btn.disabled=true;try{await api('setClassEnabled',{classId,enabled});btn.classList.toggle('on',enabled);btn.setAttribute('onclick',`toggleSetting(this,'${classId}',${!enabled})`);toast('반 설정을 저장했습니다.')}catch(e){toast(e.message)}finally{btn.disabled=false}}
window.addEventListener('online',()=>{updateNetwork();flushQueue(false);if(Date.now()-APP.lastLoaded>300000)loadData(APP.targetDate)});window.addEventListener('offline',updateNetwork);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-APP.lastLoaded>300000&&!APP.pending.size)loadData(APP.targetDate)});window.addEventListener('beforeunload',()=>{if(APP.pending.size){const items=[...APP.pending.values()];mergeQueue(items,APP.targetDate)}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updateNetwork();const cached=readData('default');if(cached){APP.data=cached;APP.targetDate=cached.targetDate;render(cached)}if(ensureConnected()){loadData();flushQueue(false)}